FROM nginx:alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY index.html /usr/share/nginx/html/gasificado/index.html
COPY css /usr/share/nginx/html/gasificado/css
COPY js /usr/share/nginx/html/gasificado/js

EXPOSE 80
